// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.6.1
// source: tradecall.proto

package model

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CallType int32

const (
	CallType_UNKNOWN CallType = 0
	CallType_BUY     CallType = 1
	CallType_SELL    CallType = 2
)

// Enum value maps for CallType.
var (
	CallType_name = map[int32]string{
		0: "UNKNOWN",
		1: "BUY",
		2: "SELL",
	}
	CallType_value = map[string]int32{
		"UNKNOWN": 0,
		"BUY":     1,
		"SELL":    2,
	}
)

func (x CallType) Enum() *CallType {
	p := new(CallType)
	*p = x
	return p
}

func (x CallType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallType) Descriptor() protoreflect.EnumDescriptor {
	return file_tradecall_proto_enumTypes[0].Descriptor()
}

func (CallType) Type() protoreflect.EnumType {
	return &file_tradecall_proto_enumTypes[0]
}

func (x CallType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallType.Descriptor instead.
func (CallType) EnumDescriptor() ([]byte, []int) {
	return file_tradecall_proto_rawDescGZIP(), []int{0}
}

type TradeCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action CallType             `protobuf:"varint,1,opt,name=action,proto3,enum=model.CallType" json:"action,omitempty"`
	Stock  string               `protobuf:"bytes,2,opt,name=stock,proto3" json:"stock,omitempty"`
	Units  int32                `protobuf:"varint,3,opt,name=units,proto3" json:"units,omitempty"`
	Price  float32              `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Time   *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *TradeCall) Reset() {
	*x = TradeCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradecall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeCall) ProtoMessage() {}

func (x *TradeCall) ProtoReflect() protoreflect.Message {
	mi := &file_tradecall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeCall.ProtoReflect.Descriptor instead.
func (*TradeCall) Descriptor() ([]byte, []int) {
	return file_tradecall_proto_rawDescGZIP(), []int{0}
}

func (x *TradeCall) GetAction() CallType {
	if x != nil {
		return x.Action
	}
	return CallType_UNKNOWN
}

func (x *TradeCall) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *TradeCall) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *TradeCall) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeCall) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_tradecall_proto protoreflect.FileDescriptor

var file_tradecall_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x09, 0x54, 0x72,
	0x61, 0x64, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x27, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x2a, 0x2a, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42,
	0x55, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x02, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tradecall_proto_rawDescOnce sync.Once
	file_tradecall_proto_rawDescData = file_tradecall_proto_rawDesc
)

func file_tradecall_proto_rawDescGZIP() []byte {
	file_tradecall_proto_rawDescOnce.Do(func() {
		file_tradecall_proto_rawDescData = protoimpl.X.CompressGZIP(file_tradecall_proto_rawDescData)
	})
	return file_tradecall_proto_rawDescData
}

var file_tradecall_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tradecall_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tradecall_proto_goTypes = []interface{}{
	(CallType)(0),               // 0: model.CallType
	(*TradeCall)(nil),           // 1: model.TradeCall
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_tradecall_proto_depIdxs = []int32{
	0, // 0: model.TradeCall.action:type_name -> model.CallType
	2, // 1: model.TradeCall.time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tradecall_proto_init() }
func file_tradecall_proto_init() {
	if File_tradecall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tradecall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tradecall_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tradecall_proto_goTypes,
		DependencyIndexes: file_tradecall_proto_depIdxs,
		EnumInfos:         file_tradecall_proto_enumTypes,
		MessageInfos:      file_tradecall_proto_msgTypes,
	}.Build()
	File_tradecall_proto = out.File
	file_tradecall_proto_rawDesc = nil
	file_tradecall_proto_goTypes = nil
	file_tradecall_proto_depIdxs = nil
}
